/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary, #000000)',
        'on-primary': 'var(--color-on-primary, #ffffff)',
        'primary-container': 'var(--color-primary-container, #1b1b1b)',
        'on-primary-container': 'var(--color-on-primary-container, #848484)',
        'primary-fixed': 'var(--color-primary-fixed, #e2e2e2)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim, #c6c6c6)',
        'on-primary-fixed': 'var(--color-on-primary-fixed, #1b1b1b)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant, #474747)',
        'inverse-primary': 'var(--color-inverse-primary, #c6c6c6)',
        secondary: 'var(--color-secondary, #5e5e5e)',
        'on-secondary': 'var(--color-on-secondary, #ffffff)',
        'secondary-container': 'var(--color-secondary-container, #e1dfdf)',
        'on-secondary-container': 'var(--color-on-secondary-container, #626262)',
        'secondary-fixed': 'var(--color-secondary-fixed, #e4e2e2)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim, #c7c6c6)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed, #1b1c1c)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant, #464747)',
        tertiary: 'var(--color-tertiary, #000000)',
        'on-tertiary': 'var(--color-on-tertiary, #ffffff)',
        'tertiary-container': 'var(--color-tertiary-container, #1b1b1b)',
        'on-tertiary-container': 'var(--color-on-tertiary-container, #848484)',
        'tertiary-fixed': 'var(--color-tertiary-fixed, #e2e2e2)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim, #c6c6c6)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed, #1b1b1b)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant, #474747)',
        error: 'var(--color-error, #ba1a1a)',
        'on-error': 'var(--color-on-error, #ffffff)',
        'error-container': 'var(--color-error-container, #ffdad6)',
        'on-error-container': 'var(--color-on-error-container, #93000a)',
        background: 'var(--color-background, #f9f9f9)',
        'on-background': 'var(--color-on-background, #1b1b1b)',
        surface: 'var(--color-surface, #f9f9f9)',
        'surface-dim': 'var(--color-surface-dim, #dadada)',
        'surface-bright': 'var(--color-surface-bright, #f9f9f9)',
        'surface-container-lowest': 'var(--color-surface-container-lowest, #ffffff)',
        'surface-container-low': 'var(--color-surface-container-low, #f3f3f3)',
        'surface-container': 'var(--color-surface-container, #eeeeee)',
        'surface-container-high': 'var(--color-surface-container-high, #e8e8e8)',
        'surface-container-highest': 'var(--color-surface-container-highest, #e2e2e2)',
        'on-surface': 'var(--color-on-surface, #1b1b1b)',
        'on-surface-variant': 'var(--color-on-surface-variant, #4c4546)',
        'inverse-surface': 'var(--color-inverse-surface, #303030)',
        'inverse-on-surface': 'var(--color-inverse-on-surface, #f1f1f1)',
        'surface-variant': 'var(--color-surface-variant, #e2e2e2)',
        'surface-tint': 'var(--color-surface-tint, #5e5e5e)',
        outline: 'var(--color-outline, #7e7576)',
        'outline-variant': 'var(--color-outline-variant, #cfc4c5)',
        'indigo-accent': '#630ed4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        'section-gap': '80px',
        'panel-padding': '40px',
        'card-padding': '24px',
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '60px',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
        display: ['Geist', 'sans-serif'],
        body: ['Geist', 'sans-serif'],
        label: ['Geist Mono', 'monospace'],
      },
      fontSize: {
        'h1': ['80px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'h1-mobile': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['56px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'h3': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'blink': 'blink 1s step-end infinite',
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'skill-fill': 'skillFill 1.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-15px)' },
        },
        blink: {
          'from, to': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        skillFill: {
          from: { width: '0%' },
          to: { width: 'var(--skill-percent)' },
        },
      },
    },
  },
  plugins: [],
};
